apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Buddhiprakash-jain/argocd.git'
    path: flask_linux_cmd
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: helmns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

