apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myd
  name: myd
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myd
  template:
    metadata:
      labels:
        app: myd
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
