apiVersion: v1
kind: Service
metadata:
  labels:
    app: newmyd
  name: newmyd
  namespace: default
spec:
  ports:
  - nodePort: 31849
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: newmyd
  type: NodePort
